### ISSUE TITLE
Find a better way to show long contents in well

### ISSUE THREAD

**Issue by Zahen** [abolis-biotechnologies/plate-maker#4]
When content is too long, the actual implementation:
- Cut the content and replace the much more by .. which can be painful for users when they want see all at the same time.
- Show the difference (the letters that differ) between well contents by replacing the common letters using a *.

This implementation IMO ( @Zahen ):
- isn't a good choice in term of UI/UX
- add complexities to the code which can annoying future maintainers

So, we should find a best and a simple way to show these contents.

**Comment by ArnaudPel** [comment]
@Zahen when writing an issue (or a review comment), only saying *isn't a good choice in term of UI/UX*, as you did above, is **not** a good practice.

You need to detail what you think is wrong, and, most importantly, *what you have in mind to make it better*. For example, if you think the code was better before, explicitly suggest a rollback of the offending commit(s).

Now on the specific UI/UX subject, our users should be the only judges anyway, so we can submit the question to them if you feel it necessary.

Lastly, IMO your description of the current implementation is incorrect. The change I pushed does not *replace the common letters*, it *replaces the longest common substring*, which is very different.

**Comment by Zahen** [comment]
@ArnaudPel, first of all, this issue is not opened to criticize our tool (Plate-Maker) or the changes you brought to the tool. You made a good change to enhance the data visualization of the long contents, and I should thank you for it.

To be more simple and explicit about this issue, this tool was developed to give biologists a simple and a powerful way to fill plates. The initial design provides a way to show each content within each well (inside the well border). This solution works fine (IMO) if the content is short (<= 10 letters for example depending on the screen resolution), but if the content is more long, the tool cuts the content and replaces the exceeded letters by "..." according to a predefined threshold, so the reading of this content become painful. You (@ArnaudPel) proposed and integrated a solution based on replacing "the longest common substring" to be more efficient for showing hiding letters (replaced initially be "...") when wells have same contents. This solution can be of benefits, like you said, our users should be the only judges. But IMO, neither the initial solution, nor your solution are good to simply visualize long contents. If I put myself in the place of a user, reading these long contents is very hard to me, but I am not a biologist :) Also, I am not a UX/UI designer to give the best solution, we can therefore make a brainstorming (me @Zahen and you @ArnaudPel) to try to find an innovative way to show a long content within a well, or simply consulting a real UX/UI designer.

Before I finish this comment, I would thank you again for the changes you made to this tool, and if you find that this issue has no sense, I will be fine if you closed.

To finish, I like to find a minimalist (less codes), simple (need a good brainstorming) and powerful (provide users with all data they need) solution to resolve this issue.

**Comment by ArnaudPel** [comment]
Ok thank you @Zahen, your intent regarding this issue is more clear to me now.

I took the liberty to reword the title, and would like to suggest a reworded version of this issue as well, so as to give a clear example of what I meant above (on *positive commenting*, if I may say):

----------------------------------------------------------
When a content is too long to fit on the well's screen space, the current implementation:

- Replaces the longest common substring across all well contents by *, when applicable, so as to save space by removing redundant information first
- Truncates the remaining contents, by replacing the trailing substring of necessary length by `..`

While this implementation already provides a working tool for our users, I (@Zahen) hope we can find a even better approach to solve this issue.

Ideally, the next implementation should:
- always display the full contents
- make the code more simple than the current implementation

Since I currently have no idea on how to achieve this, I open this issue so as to have a place where we can brainstorm ideas.

----------------------------------------------------------
Voila, here was my example of rewording, I hope you feel it more pleasing and inspiring, as I do. 

One benefit of this state of mind IMO is that, in the advent of us never being able to find a better solution, we will be left with a *working tool for our users*, and not a *bad choice in term of UI/UX*. Better for morale ;)

**Comment by Zahen** [comment]
Ok, your rewording looks better for me. May I suggest to close this issue and open another one with your version?
Thank you

**Comment by ArnaudPel** [comment]
Cool, sure, we can do that. Can I let you do it ?
